/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCheckbox: typeof import('./src/components/form/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./src/components/form/BaseInput.vue')['default']
    BaseRadio: typeof import('./src/components/form/BaseRadio.vue')['default']
    BaseRadioGroup: typeof import('./src/components/form/BaseRadioGroup.vue')['default']
    BaseSelect: typeof import('./src/components/form/BaseSelect.vue')['default']
    CardImg: typeof import('./src/components/cards/cardImg/CardImg.vue')['default']
    ContainerCards: typeof import('./src/components/ContainerCards.vue')['default']
    FormSubmit: typeof import('./src/components/form/FormSubmit.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NavList: typeof import('./src/components/nav/NavList.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleCard: typeof import('./src/components/cards/card/SingleCard.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
